; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, GroupBox, x8 y1 w106 h70, Size
Gui Add, Text, x16 y18 w35 h20 +0x200, Width:
Gui Add, Text, x16 y42 w35 h20 +0x200, Height:
Gui Add, Edit, x52 y19 w32 h20
Gui Add, Edit, x52 y42 w32 h20
Gui Add, GroupBox, x8 y72 w110 h70, Printer
Gui Add, Text, x16 y92 w40 h20 +0x200, Speed:
Gui Add, Edit, x64 y93 w20 h20 +0x1
Gui Add, Text, x16 y116 w40 h20 +0x200, Density
Gui Add, Edit, x64 y116 w20 h20 +0x1
Gui Add, GroupBox, x123 y72 w110 h70, Direction
Gui Add, Radio, vMyRadio x135 y92 w64 h20, Normal
Gui Add, Radio, , Inverse
Gui Add, Text, x87 y19 w18 h20 +0x200, mm
Gui Add, Text, x87 y42 w18 h20, mm
Gui Add, GroupBox, x118 y1 w115 h70, Coordinates
Gui Add, Text, x124 y18 w16 h20 +0x200, X1:
Gui Add, Text, x124 y40 w16 h20 +0x200, Y1:
Gui Add, Edit, x141 y19 w32 h20
Gui Add, Edit, x141 y41 w32 h20
Gui Add, Text, x178 y18 w16 h20 +0x200, X2:
Gui Add, Text, x178 y40 w16 h20 +0x200, Y2:
Gui Add, Text, x16 y160 w47 h20 +0x200, Delay ms:
Gui Add, Edit, x64 y160 w30 h20
Gui Add, Text, x130 y160 w40 h20 +0x200, Date:
Gui Add, Edit, x160 y160 w55 h20
Gui Add, Button, hWndhEditBtn x68 y194 w80 h23, &Save
Gui Add, Button, x152 y194 w80 h23, &Cancel
Gui Add, GroupBox, x8 y143 w225 h44, Misc
Gui Add, Edit, x195 y18 w32 h20
Gui Add, Edit, x195 y40 w32 h20

Gui Show, w240 h225, Settings
Return

GuiEscape:
GuiClose:
    ExitApp
